objects/Tab_Panel__mdt.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TabPanel_Unique_Key__c</fullName>
        <inlineHelpText>Enter unique key to identify template to pick.</inlineHelpText>
        <label>TabPanel Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tab_Icon_Name__c</fullName>
        <label>Tab Icon Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tab_Order__c</fullName>
        <label>Tab Order</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tab Panel Wizard</label>
    <pluralLabel>Tab Panel Wizard</pluralLabel>
</CustomObject>

objects/TabPanel_Component__mdt.object
<CustomObject>
    <description>This custom metadata type will be used to store Tab Panel setup information.</description>
    <fields>
        <fullName>Action_1__c</fullName>
        <inlineHelpText>Value should contain the Component Label that should be opened. Component name will be underscore separated.
For example, if component name is &quot;Example 1&quot; then a button will appear with &quot;Example 1&quot; and component name should be &quot;Example_1&quot;.</inlineHelpText>
        <label>Action 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_2__c</fullName>
        <inlineHelpText>Value should contain the Component Label that should be opened. Component name will be underscore separated.
For example, if component name is &quot;Example 1&quot; then a button will appear with &quot;Example 1&quot; and component name should be &quot;Example_1&quot;.</inlineHelpText>
        <label>Action 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Collapsed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Collapsed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>TabPanel_Components</relationshipLabel>
        <relationshipName>TabPanel_Components</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Screen_Type__c</fullName>
        <label>Screen Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Section</fullName>
                    <default>true</default>
                    <label>Section</label>
                </value>
                <value>
                    <fullName>Table</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Actions_Supported__c</fullName>
        <label>Section Actions Supported</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>U</fullName>
                    <label>Edit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Icon_Name__c</fullName>
        <inlineHelpText>Copy the icon qualified name from SLDS library.</inlineHelpText>
        <label>Section Icon Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Order__c</fullName>
        <label>Section Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tab_Panel__c</fullName>
        <label>Tab Panel</label>
        <referenceTo>Tab_Panel__mdt</referenceTo>
        <relationshipLabel>TabPanel Components</relationshipLabel>
        <relationshipName>TabPanel_Components</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Table_Actions_Supported__c</fullName>
        <label>Table Actions Supported</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>R</fullName>
                    <default>true</default>
                    <label>View</label>
                </value>
                <value>
                    <fullName>U</fullName>
                    <label>Edit</label>
                </value>
                <value>
                    <fullName>D</fullName>
                    <label>Delete</label>
                </value>
                <value>
                    <fullName>UD</fullName>
                    <label>Edit/Delete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TabPanel Component</label>
    <pluralLabel>TabPanel Components</pluralLabel>
</CustomObject>

GenericTabset Builder/main/default/classes/LTX_TabPanel_CC.cls
public with sharing class LTX_TabPanel_CC {
    /*
     * This method will return a sorted list of tab configs
     * tab name -> tab section components
    */
    @AuraEnabled(cacheable=true)
    public static map<String, list<TabPanel_Component__mdt>> getTabPanel(String tabPanelTemplateId){
        map<String, list<TabPanel_Component__mdt>> unorderedTabMap = new map<String,list<TabPanel_Component__mdt>>();
        map<String, list<TabPanel_Component__mdt>> orderedTabMap = new map<String,list<TabPanel_Component__mdt>>();
        map<String, String> tabLabelMap = new map<String, String>();
        for(TabPanel_Component__mdt rec: [SELECT Id, Label, MasterLabel, Object_Name__r.QualifiedApiName, FieldSet__c, 
                                          Section_Actions_Supported__c, Table_Actions_Supported__c, Screen_Type__c, 
                                          Action_1__c, Action_2__c, Reference_Id__c, Section_Icon_Name__c, Section_Order__c,
                                          Tab_Panel__r.Tab_Icon_Name__c,Tab_Panel__r.Tab_Order__c, Tab_Panel__r.MasterLabel,
                                          Tab_Panel__r.Default__c, Is_Collapsed__c
                                          FROM TabPanel_Component__mdt 
                                          where Is_Active__c=true and Tab_Panel__r.TabPanel_Unique_Key__c=:tabPanelTemplateId
                                          order by Section_Order__c asc])
        {
            if(unorderedTabMap.containsKey(rec.Tab_Panel__r.Tab_Order__c)){
                unorderedTabMap.get(rec.Tab_Panel__r.Tab_Order__c).add(rec);
            }else{
                unorderedTabMap.put(rec.Tab_Panel__r.Tab_Order__c,new list<TabPanel_Component__mdt>{rec});
            }
            tabLabelMap.put(rec.Tab_Panel__r.Tab_Order__c, rec.Tab_Panel__r.MasterLabel);
        }
        //Sorting the keys using list as we can't sort set
        list<String> deciList = new list<String>();
        deciList.addAll(unorderedTabMap.keySet());
        deciList.sort();
        for(String rec: deciList){
            orderedTabMap.put(tabLabelMap.get(rec),unorderedTabMap.get(rec));
            System.debug('****order:-> :'+unorderedTabMap.get(rec));
        }
        System.debug('****orderedTabMap:'+orderedTabMap);
        return orderedTabMap;
    }
}